#!/bin/sh /etc/rc.common

START=98
STOP=11
USE_PROCD=1

. /usr/lib/singbox/common.sh

start_service() {
    sbox_load
    [ "$UPDATE_ON_BOOT" = 1 ] || return 0
    [ -n "$CONFIG_URL" ] || return 0
    procd_open_instance main
    procd_set_param command /usr/sbin/singbox-update-config --boot
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param term_timeout 5
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger singbox
}
