#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

. /lib/functions.sh

load_cfg() {
    config_load singbox
    config_get ENABLED main enabled 0
    config_get PROG main bin_path /etc/sbox/sing-box
    config_get RES_DIR main sbox_dir /etc/sbox
    config_get CONF main config_path /etc/sbox/config.json
    config_get RESPAWN_THRESHOLD main respawn_threshold 3600
    config_get RESPAWN_TIMEOUT main respawn_timeout 5
    config_get RESPAWN_RETRY main respawn_retry 5
}

start_service() {
    load_cfg
    [ "$ENABLED" = "1" ] || return 0
    [ -x "$PROG" ] || return 1
    [ -f "$CONF" ] || return 1
    procd_open_instance
    procd_set_param command $PROG run -D $RES_DIR -c $CONF
    procd_set_param user root
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "$RESPAWN_THRESHOLD" "$RESPAWN_TIMEOUT" "$RESPAWN_RETRY"
    procd_close_instance
    echo "sing-box is started!"
}

stop_service() {
    service_stop $PROG
    # Ensure firewall rules are cleaned up so we fall back to direct connection
    sh /etc/sbox/sbox_tproxy_stop.sh
    echo "sing-box is stopped!"
}

reload_service() {
    stop
    sleep 2s
    echo "sing-box is restarted!"
    start
}
